apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: echo-replica
spec:
  replicas: 4
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo
        image: registry.cluster.wik.cloud/public/echo
        ports:
        - containerPort: 8080

# SERVICE
---
apiVersion: v1
kind: Service
metadata:
  name: replica-service
spec:
  selector:
    app: echo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080    

    